apiVersion: apps/v1
kind: Deployment
metadata:
  name: vroapp
  labels: 
    app: vroapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vroapp
  template:
    metadata:
      labels:
        app: vroapp
  spec:
      containers:
      - name: vroapp
        image: {{ .Values.appimage}}: {{ .Values.apptag}}
        ports:
        - name: vroapp-port
          containerPort: 8080
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', 'until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
